name: cochise
description: A tool to help coachs
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_flutter: ^1.0.0
  amplify_storage_s3: ^1.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.8.3
  riverpod_annotation: ^2.0.1
  timelines: ^0.1.0
  uuid: ^4.5.1


dev_dependencies:
  amplify_lints: ^3.0.0
  build_runner:
  custom_lint:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.1.3
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - images/cochise.png